pfcp:
  addr: "10.0.60.3"
  nodeID: "10.0.60.3"
  retransTimeout: 1s
  maxRetrans: 3
gtpu:
  forwarder: "wmnsk/go-gtp"
  tunInterfaceName: upf
  ifList:
    - addr: "10.0.10.3"
      type: N3
    - addr: "10.0.20.3"
      type: N9
dnnList:
  - dnn: "sliceA"
    cidr: "10.0.200.0/24"
