pfcp:
  addr: "10.0.60.4"
  nodeID: "10.0.60.4"
  retransTimeout: 1s
  maxRetrans: 3
gtpu:
  forwarder: "wmnsk/go-gtp"
  tunInterfaceName: gnb
  ifList:
    - addr: "10.0.20.2"
      type: N9
dnnList:
  - dnn: "sliceA"
    cidr: "10.0.200.0/24"
